#!/usr/bin/env bash
set -euo pipefail

# ─── Argument defaults ────────────────────────────────────────────────────────
DB_HOST="localhost"
DB_PORT="3306"
DB_USER=""
DB_PASS=""
DB_NAME="openmrs"
BATCH_ID=""
DOCKER_CONTAINER=""

# ─── Usage ────────────────────────────────────────────────────────────────────
usage() {
    echo ""
    echo "Usage (direct) : $0 -u <user> [-p <password>] -d <database> [-b <batch_id>] [-h <host>] [-P <port>]"
    echo "Usage (Docker) : $0 -u <user> [-p <password>] -d <database> [-b <batch_id>] -c <container>"
    echo ""
    echo "  -u  MySQL username        (required)"
    echo "  -p  MySQL password        (optional — prompted securely if not provided)"
    echo "  -d  Database name         (required)"
    echo "  -b  Batch ID to roll back (optional — lists available batches if omitted)"
    echo "  -h  Host                  (default: localhost, direct mode only)"
    echo "  -P  Port                  (default: 3306,     direct mode only)"
    echo "  -c  Docker container name"
    echo ""
    echo "  The rollback uses fhir_diag_report_migration_log to identify exactly"
    echo "  which rows were created in the target batch. Only those rows are deleted."
    echo "  Rows created by the React UI after migration are never touched."
    echo ""
    exit 1
}

while getopts "h:P:u:p:d:b:c:" opt; do
    case $opt in
        h) DB_HOST="$OPTARG" ;;
        P) DB_PORT="$OPTARG" ;;
        u) DB_USER="$OPTARG" ;;
        p) DB_PASS="$OPTARG" ;;
        d) DB_NAME="$OPTARG" ;;
        b) BATCH_ID="$OPTARG" ;;
        c) DOCKER_CONTAINER="$OPTARG" ;;
        *) usage ;;
    esac
done

if [[ -z "$DB_USER" || -z "$DB_NAME" ]]; then
    usage
fi

if [[ -z "$DB_PASS" ]]; then
    read -r -s -p "  Enter password for $DB_USER: " DB_PASS
    echo ""
    echo ""
fi

if [[ -n "$DOCKER_CONTAINER" ]]; then
    MYSQL_CMD="docker exec -e MYSQL_PWD=$DB_PASS $DOCKER_CONTAINER mysql -u $DB_USER $DB_NAME"
    MYSQL_PIPE_CMD="docker exec -i -e MYSQL_PWD=$DB_PASS $DOCKER_CONTAINER mysql -u $DB_USER $DB_NAME"
else
    MYSQL_CMD="mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASS $DB_NAME"
    MYSQL_PIPE_CMD="mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASS $DB_NAME"
fi

echo ""

# ─── Check that the migration log table exists ────────────────────────────────
LOG_TABLE_EXISTS=$($MYSQL_CMD --skip-column-names -e "
SELECT COUNT(*) FROM information_schema.tables
WHERE table_schema = DATABASE()
  AND table_name = 'fhir_diag_report_migration_log';
" 2>&1)

if [[ "$LOG_TABLE_EXISTS" -eq 0 ]]; then
    echo "  ERROR: fhir_diag_report_migration_log table does not exist."
    echo "  The migration script must have run at least once to create this table."
    echo ""
    exit 1
fi

# ─── If no batch_id supplied, list available batches and prompt ───────────────
if [[ -z "$BATCH_ID" ]]; then
    echo "  Available migration batches:"
    echo ""

    BATCH_LIST=$($MYSQL_CMD --skip-column-names -e "
    SELECT
        batch_id,
        COUNT(*)        AS reports,
        MIN(migrated_at) AS started_at,
        MAX(migrated_at) AS finished_at
    FROM fhir_diag_report_migration_log
    GROUP BY batch_id
    ORDER BY MIN(migrated_at) DESC;
    " 2>&1)

    if [[ -z "$BATCH_LIST" ]]; then
        echo "  No migration batches found in fhir_diag_report_migration_log."
        echo "  Nothing to roll back."
        echo ""
        exit 0
    fi

    printf "  %-38s | %8s | %-20s | %-20s\n" "Batch ID" "Reports" "Started at" "Finished at"
    printf "  %s\n" "----------------------------------------------------------------------------------------"
    echo "$BATCH_LIST" | while IFS=$'\t' read -r bid cnt started finished; do
        printf "  %-38s | %8s | %-20s | %-20s\n" "$bid" "$cnt" "$started" "$finished"
    done
    echo ""

    read -r -p "  Enter batch ID to roll back: " BATCH_ID
    echo ""

    if [[ -z "$BATCH_ID" ]]; then
        echo "  No batch ID entered. Rollback aborted."
        echo ""
        exit 0
    fi
fi

# ─── Validate batch ID format (before any DB call — prevents SQL injection) ───
# Accepted formats:
#   UUID          — generated by SELECT UUID() in the migration script
#   batch_DATE_TIME — fallback when UUID() is unavailable
if ! [[ "$BATCH_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ || \
        "$BATCH_ID" =~ ^batch_[0-9]{8}_[0-9]{6}$ ]]; then
    echo "  ERROR: Batch ID '$BATCH_ID' has an invalid format (${#BATCH_ID} chars)."
    echo "  Expected: UUID (36 chars)  e.g. 550e8400-e29b-41d4-a716-446655440000"
    echo "            or    batch_YYYYMMDD_HHMMSS   e.g. batch_20260717_103045"
    echo "  Tip: copy-paste directly from the batch list above to avoid typos."
    echo ""
    exit 1
fi

# ─── Validate the batch ID exists in the log ─────────────────────────────────
DELETE_COUNT=$($MYSQL_CMD --skip-column-names -e "
SELECT COUNT(*)
FROM fhir_diag_report_migration_log
WHERE batch_id = '$BATCH_ID';
" 2>&1)

if [[ "$DELETE_COUNT" -eq 0 ]]; then
    echo "  ERROR: Batch ID '$BATCH_ID' not found in fhir_diag_report_migration_log."
    echo "  Run without -b to list available batch IDs."
    echo ""
    exit 1
fi

# ─── Warning ──────────────────────────────────────────────────────────────────
echo "============================================================"
echo "  Rollback: batch $BATCH_ID"
echo "============================================================"
echo ""
echo "  This will delete $DELETE_COUNT fhir_diagnostic_report rows"
echo "  and their child records (results, performers, service"
echo "  requests, presented forms) for this batch only."
echo ""
echo "  Rows created by the React UI after migration are identified"
echo "  by their absence from the migration log and will NOT be"
echo "  touched by this rollback."
echo ""
echo "  The obs table is never modified."
echo "============================================================"
echo ""

read -r -p "  Type 'YES' to confirm rollback of $DELETE_COUNT diagnostic report rows: " CONFIRM
echo ""

if [[ "$CONFIRM" != "YES" ]]; then
    echo "  Rollback aborted by user. No data was modified."
    echo ""
    exit 0
fi

# ─── Execute rollback ─────────────────────────────────────────────────────────
echo "  Executing rollback for batch $BATCH_ID ..."
echo ""

set +e
ROLLBACK_OUTPUT=$($MYSQL_PIPE_CMD --skip-column-names 2>&1 <<ROLLBACKSQL
START TRANSACTION;

CREATE TEMPORARY TABLE tmp_rollback_dr_ids AS
SELECT diagnostic_report_id
FROM fhir_diag_report_migration_log
WHERE batch_id = '$BATCH_ID';

DELETE FROM fhir_diagnostic_report_presented_form
WHERE diagnostic_report_id IN (SELECT diagnostic_report_id FROM tmp_rollback_dr_ids);
SELECT ROW_COUNT();

DELETE FROM fhir_diagnostic_report_service_request
WHERE diagnostic_report_id IN (SELECT diagnostic_report_id FROM tmp_rollback_dr_ids);
SELECT ROW_COUNT();

DELETE FROM fhir_diagnostic_report_results
WHERE diagnostic_report_id IN (SELECT diagnostic_report_id FROM tmp_rollback_dr_ids);
SELECT ROW_COUNT();

DELETE FROM fhir_diagnostic_report_performers
WHERE diagnostic_report_id IN (SELECT diagnostic_report_id FROM tmp_rollback_dr_ids);
SELECT ROW_COUNT();

DELETE FROM fhir_diagnostic_report
WHERE diagnostic_report_id IN (SELECT diagnostic_report_id FROM tmp_rollback_dr_ids);
SELECT ROW_COUNT();

DELETE FROM fhir_diag_report_migration_log
WHERE batch_id = '$BATCH_ID';
SELECT ROW_COUNT();

DROP TEMPORARY TABLE tmp_rollback_dr_ids;

COMMIT;
ROLLBACKSQL
)
DELETE_EXIT=$?
set -e

if [[ $DELETE_EXIT -ne 0 ]]; then
    echo "  ERROR: Rollback failed."
    echo "$ROLLBACK_OUTPUT"
    echo "  The transaction was rolled back — no data was deleted."
    echo ""
    exit 1
fi

# Parse the six ROW_COUNT() values returned by the SQL (one per DELETE).
# Uses sed instead of mapfile for bash 3.2 compatibility (macOS default shell).
ROLLBACK_NUMS=$(echo "$ROLLBACK_OUTPUT" | grep -E '^[0-9]+$')
DEL_PRESENTED_FORM=$(echo "$ROLLBACK_NUMS" | sed -n '1p')
DEL_SERVICE_REQUEST=$(echo "$ROLLBACK_NUMS" | sed -n '2p')
DEL_RESULTS=$(echo "$ROLLBACK_NUMS" | sed -n '3p')
DEL_PERFORMERS=$(echo "$ROLLBACK_NUMS" | sed -n '4p')
DEL_DIAG_REPORT=$(echo "$ROLLBACK_NUMS" | sed -n '5p')
DEL_LOG=$(echo "$ROLLBACK_NUMS" | sed -n '6p')
DEL_PRESENTED_FORM=${DEL_PRESENTED_FORM:-0}
DEL_SERVICE_REQUEST=${DEL_SERVICE_REQUEST:-0}
DEL_RESULTS=${DEL_RESULTS:-0}
DEL_PERFORMERS=${DEL_PERFORMERS:-0}
DEL_DIAG_REPORT=${DEL_DIAG_REPORT:-0}
DEL_LOG=${DEL_LOG:-0}

echo "  Rollback complete."
echo ""
echo "  +-----------------------------------------------------------------+"
echo "  |  ROLLBACK SUMMARY                                               |"
echo "  +-----------------------------------------------------------------+"
printf "  |  Batch ID                              : %-20s|\n" "$BATCH_ID"
printf "  |  fhir_diagnostic_report deleted        : %-20s|\n" "$DEL_DIAG_REPORT"
printf "  |  fhir_diagnostic_report_results        : %-20s|\n" "$DEL_RESULTS"
printf "  |  fhir_diagnostic_report_performers     : %-20s|\n" "$DEL_PERFORMERS"
printf "  |  fhir_diagnostic_report_service_request: %-20s|\n" "$DEL_SERVICE_REQUEST"
printf "  |  fhir_diagnostic_report_presented_form : %-20s|\n" "$DEL_PRESENTED_FORM"
printf "  |  fhir_diag_report_migration_log        : %-20s|\n" "$DEL_LOG"
echo "  +-----------------------------------------------------------------+"
echo ""
echo "  The obs table was not modified."
echo ""