name: Build and Upload OpenMRS Demo DB Images
on:
  push:
    branches:
      - master
      - demo-images
    paths:
      - "demo/db-backups/**"
      - ".github/workflows/openmrs-demo-db-build.yml"

jobs:
  build-publish-docker-helm:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_images: [
          { image: 'mysql:5.7', platforms: 'linux/amd64' },
          { image: 'mysql:8.0', platforms: 'linux/amd64, linux/arm64' },
          { image: 'mariadb:10.9', platforms: 'linux/amd64, linux/arm64' },
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Generate Tag
        run: echo "IMAGE_TAG=demo-$(echo ${{ matrix.base_images.image }} | sed -r 's/://g')" >> $GITHUB_ENV
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: demo/db-backups/
          platforms: ${{ matrix.base_images.platforms }}
          file: demo/db-backups/openmrsDemoDB.Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base_images.image }}
          push: false
          tags: bahmni/openmrs-db:${{ env.IMAGE_TAG }}
